SET NAMES utf8mb4;

INSERT INTO
    `products` (
        `id`,
        `slug`,
        `name`,
        `image`,
        `image_mime`,
        `image_size`,
        `description`,
        `active`,
        `category_id`,
        `reviews_count`,
        `reviews_avg_rating`,
        `deleted_at`,
        `created_at`,
        `updated_at`
    )
VALUES (
        2,
        'piepjack-t-shirt-speziel',
        'Piepjack T-Shirt Speziel',
        'https://placehold.co/600x400.png?text=Product+Image',
        'image/jpeg',
        1586,
        'Architecto explicabo enim est id voluptatem. Facilis cupiditate quibusdam eum est consequatur. Exercitationem magni voluptatem qui eos consequatur deleniti ipsa. Officiis quis sequi deleniti iusto minus commodi ut sit.',
        0,
        1,
        2,
        2.50,
        '2026-04-01 20:36:37',
        '2025-07-13 22:26:41',
        '2026-04-01 20:36:37'
    ),
    (
        11,
        'zip-sweter-jacke',
        'Zip Sweter Jacke',
        'https://placehold.co/600x400.png?text=Product+Image',
        'image/jpeg',
        617,
        'Id voluptas saepe consectetur tenetur cupiditate. Est accusamus aut sed omnis corrupti et eos. Nihil corporis officia adipisci reprehenderit laboriosam dignissimos dolorum illum. Et et voluptas quis.',
        1,
        2,
        0,
        NULL,
        '2026-04-01 20:36:13',
        '2025-07-13 22:26:41',
        '2026-04-01 20:36:13'
    ),
    (
        41,
        'piepjack-accessory',
        'Piepjack Accessory',
        'https://placehold.co/600x400.png?text=Product+Image',
        'image/jpeg',
        158,
        'Ab provident exercitationem non eligendi fuga dolorem soluta amet. Et aut consequatur laboriosam ipsam et natus. Quas voluptatem voluptatibus facere. Sunt aliquam ipsa alias molestiae et ab.',
        0,
        5,
        3,
        3.67,
        '2026-04-01 20:36:32',
        '2025-07-13 22:26:42',
        '2026-04-01 20:36:32'
    ),
    (
        62,
        'dream-zip-hoodie',
        'DREAM ZIP HOODIE',
        'https://testing.piepjack-clothing.de/storage/images/jh5jjNJilm/pj009-design-front-NyiHu5Ny.jpeg',
        'image/jpeg',
        103044,
        '<p><em>Der DREAM ZIP HOODIE steht für deine Ziele und Träume, die du eines Tages zur Realität machst.</em></p><p>Lockerer Fit, maximaler Komfort und edle Details vereinen sich mit einem hochwertigen Off-White Puff Print sowie erstklassigem Material, für ein luxuriöses und angenehmes Tragegefühl.</p><p></p><p><span style=\"color: #fffbb9\"><strong>DETAILS</strong></span></p><p></p><ul><li><p><em>- 70% Baumwolle, 30% Polyester</em></p></li><li><p><em>- 330 g/m Hochwertiger, schwerer Stoff</em></p></li><li><p><em>- Brushed Fleece (angeraut innen)</em></p></li><li><p><em>- Oversize Fit</em></p></li><li><p><em>- Unisex</em></p><p><em>- Made in Turkey</em></p></li></ul><p></p><p><span style=\"color: #fffbb9\"><strong>PASSFORM</strong></span></p><p></p><p>Das Model ist ca. xxxxxm groß und trägt Größe x.</p><p></p><p><span style=\"color: #fffbb9\"><strong>PFLEGEHINWEISE</strong></span></p><p></p><ul><li><p>- <em>Waschbar bei 30°C</em></p></li><li><p><em>- Auf links waschen</em></p></li><li><p><em>- nicht bleichen</em></p></li><li><p><em>- Nicht in den Trockner</em></p></li><li><p><em>- Auf links bügeln</em></p></li><li><p><em>- Nicht chemisch reinigen</em></p></li></ul><p></p>',
        1,
        2,
        0,
        NULL,
        '2026-04-04 21:27:04',
        '2025-10-02 05:47:49',
        '2026-04-04 21:27:04'
    ),
    (
        63,
        'legacy-t-shirt',
        'LEGACY T-SHIRT',
        'https://testing.piepjack-clothing.de/storage/images/fiLl2IkIKo/img-3352-5CGGoiiz.PNG',
        'image/png',
        2285937,
        '<p><em>Das LEGACY T-SHIRT überzeugt durch ein cleanes Design mit minimalistischem Frontprint und auffälligem Backprint. Ein moderner, lockerer Schnitt trifft auf einen besonders weichen, hochwertigen Stoff, der sich angenehm auf der Haut anfühlt, für maximalen Komfort im Alltag.</em></p><p></p><p><span style=\"color: #fffbb9\"><strong>DETAILS</strong></span></p><p></p><ul><li><p><em>- 100% Premium Baumwolle</em></p></li><li><p><em>- Dichtgewebte Heavyweight Baumwolle - 230g/m²</em></p></li><li><p><em>- Oversize Fit</em></p></li><li><p><em>- Gut anliegender Kragen</em></p></li><li><p><em>- Unisex</em></p><p><em>- Made in Turkey</em></p></li></ul><p></p><p><span style=\"color: #fffbb9\"><strong>PASSFORM</strong></span></p><p></p><p><em>Das Model ist ca. 1,90 m groß und trägt Größe L.</em></p><p></p><p><span style=\"color: #fffbb9\"><strong>PFLEGEHINWEISE</strong></span></p><p></p><ul><li><p>- <em>Waschbar bei 30°C</em></p></li><li><p><em>- Auf links waschen</em></p></li><li><p><em>- Nicht bleichen</em></p></li><li><p><em>- Nicht in den Trockner</em></p></li><li><p><em>- Auf links bügeln</em></p></li><li><p><em>- Nicht chemisch reinigen</em></p></li></ul><ul><li><p></p></li></ul><p></p><p></p><p></p><p></p>',
        1,
        1,
        0,
        NULL,
        NULL,
        '2026-04-01 20:27:54',
        '2026-04-04 19:10:26'
    ),
    (
        64,
        'vanilla-soft-jacket',
        'VANILLA SOFT JACKET',
        'https://testing.piepjack-clothing.de/storage/images/MhY33FuZ7O/piepjack-1-mNPf6ZZZ.png',
        'image/png',
        155218,
        '<p><em>Die VANILLA SOFT JACKE überzeugt durch ihr außergewöhnlich weiches Material, den cleanen Ton-in-Ton Look in (Beige) und ihre hochwertigen Details.</em></p><p><em>Dezent, edel und gleichzeitig auffällig auf ihre eigene Art.</em></p><p></p><p><em>Maximaler Komfort trifft auf einen luxuriösen Look, perfekt für jede Jahreszeit, von kühlen Sommernächten bis in die kalte Saison.</em></p><p></p><p></p><p></p><p></p><p><span style=\"color: rgb(255, 249, 149)\"><strong>DETAILS</strong></span></p><p></p><p><em>-100% Polyester Wellsoft</em></p><ul><li><p>- 290 g/m <em>Hochwertiger, weicher Stoff</em></p></li><li><p><em>- Dezente PIEPJACK Branding - Elemente</em></p><ul><li><p><em>- Lockerer Fit</em></p></li><li><p><em>- Unisex</em></p></li><li><p><em>- Made in Turkey</em></p></li></ul></li></ul><p></p><p></p><p></p><p><span style=\"color: #fffbb9\"><strong>PASSFORM</strong></span></p><p></p><p><em>Das Model ist ca. 1,79 cm groß und trägt Größe L</em></p><p></p><p></p><p></p><p><span style=\"color: rgb(255, 249, 149)\"><strong>PFLEGEHINWEISE</strong></span></p><p></p><p><em>- Waschbar bei 30°C</em></p><ul><li><p>- Auf links waschen</p></li><li><p>- Nicht bleichen</p></li><li><p>- Nicht in den Trockner</p></li><li><p>- Auf links bügeln</p></li><li><p>- Nicht chemisch reinigen</p></li><li><p></p></li></ul>',
        1,
        3,
        0,
        NULL,
        NULL,
        '2026-04-01 20:29:23',
        '2026-04-04 21:18:01'
    ),
    (
        65,
        'dream-zip-hoodie',
        'DREAM ZIP HOODIE',
        'https://testing.piepjack-clothing.de/storage/images/5QTeeSt5ve/pj009-design-back-XUskYL01.jpeg',
        'image/jpeg',
        321734,
        '<p><em>Der DREAM ZIP HOODIE steht für deine Ziele und Träume, die du eines Tages zur Realität machst. Lockerer Fit, maximaler Komfort und edle Details vereinen sich mit einem hochwertigen Off-White Puff Print sowie erstklassigem Material, für ein luxuriöses und angenehmes Tragegefühl.</em></p><p></p><p></p><p><span style=\"color: rgb(255, 251, 185)\"><strong><em>DETAILS</em></strong></span></p><p></p><p></p><p><em>- 70% Baumwolle, 30% Polyester</em></p><p><em>- 330 g/m Hochwertiger, schwerer Stoff</em></p><p><em>- Brushed Fleece (angeraut innen)</em></p><p><em>- Oversize Fit</em></p><p><em>- Unisex</em></p><p><em>- Made in Turkey</em></p><p></p><p></p><p><span style=\"color: rgb(255, 251, 185)\"><strong><em>PASSFORM</em></strong></span></p><p></p><p><em>Das Model ist ca. xxxxxm groß und trägt Größe x.</em></p><p></p><p></p><p><span style=\"color: rgb(255, 251, 185)\"><strong><em>PFLEGEHINWEISE</em></strong></span></p><p><em>- Waschbar bei 30°C</em></p><p><em>- Auf links waschen</em></p><p><em>- nicht bleichen</em></p><p><em>- Nicht in den Trockner</em></p><p><em>- Auf links bügeln</em></p><p><em>- Nicht chemisch reinigen</em></p>',
        1,
        2,
        0,
        NULL,
        NULL,
        '2026-04-04 21:27:48',
        '2026-04-04 21:34:05'
    );
-- 2026-04-08 14:26:20 UTC